### ISSUE TITLE
Support more views

### ISSUE THREAD

**Issue by fregante** [wallabi-es/image-focus#41]
- It doesn't appear in the regular Edit Media screen: `post.php?post=12395&action=edit`  [screenshot](https://user-images.githubusercontent.com/1402241/36001088-bb6b9090-0d57-11e8-9380-604edaa0328f.png)
- It doesn't appear in the Edit Image screen (same page, after clicking Edit Image)
[screenshot](https://user-images.githubusercontent.com/1402241/36001067-ae4dc28e-0d57-11e8-9231-0e427d801029.png)
- It doesn't appear in list view: `upload.php?mode=list` (because it only links to the Edit screen)
- It doesn't appear after an upload (because it only links to the Edit screen) [screenshot](https://user-images.githubusercontent.com/1402241/36001117-d3b0951a-0d57-11e8-9eff-1e9a383cfc8d.png)
- It doesn't appear in image selection screens (e.g. when picking a featured image) [screenshot](https://user-images.githubusercontent.com/1402241/36001212-23f6ca58-0d58-11e8-9378-a5caa70fd861.png)

**Comment by DannyvanHolten** [comment]
I am sorry though. The plug-in is not maintained currently. Maybe @HarwinBorger want to pick up the changes. But I have changed from WordPress development to React development.
